#-------------------------------
# General Site Settings

menu:
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
#-------------------------------
# Contact Section

social:

- {icon: 'linkedin',  link: 'https://www.linkedin.com/in/fl%C3%A1via-de-oliveira-1953b4134/'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
